<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSVbfd7V\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSVbfd7V/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSVbfd7V.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSVbfd7V\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSVbfd7V\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SVbfd7V',
    'container.build_id' => '25ae674c',
    'container.build_time' => 1573363277,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSVbfd7V');
