<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_twig_error_test' => [['code', '_format'], ['_controller' => 'twig.controller.preview_error::previewErrorPageAction', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'invoice_list' => [[], ['_controller' => 'App\\Controller\\InvoiceController::index'], [], [['text', '/']], [], []],
    'invoice_new_step1' => [[], ['_controller' => 'App\\Controller\\InvoiceController::newStep1'], [], [['text', '/invoice/new/step1']], [], []],
    'invoice_new_step2' => [['id'], ['_controller' => 'App\\Controller\\InvoiceController::newStep2'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/invoice/new/step2']], [], []],
    'invoice_edit' => [['id'], ['_controller' => 'App\\Controller\\InvoiceController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/invoice/edit']], [], []],
    'invoice_delete' => [['id'], ['_controller' => 'App\\Controller\\InvoiceController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/invoice/delete']], [], []],
    'invoice_show' => [['id'], ['_controller' => 'App\\Controller\\InvoiceController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/invoice']], [], []],
    'index' => [[], ['_controller' => 'App\\Controller\\InvoiceController::index'], [], [['text', '/']], [], []],
];
